name: flutter_review
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
    
  get: ^4.7.2
  shared_preferences: ^2.5.3

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/ahmork.png
    - assets/images/khmer_noodle.jpg
    - assets/images/korko.jpg
    - assets/images/loklak.jpg
    - assets/images/rice.jpeg
